apiVersion: v1
kind: Secret
metadata:
  name: relay-litestream-secret
  namespace: ${namespace}
type: Opaque
stringData:
  LITESTREAM_ACCESS_KEY_ID: "${backup_access_key}"
  LITESTREAM_SECRET_ACCESS_KEY: "${backup_secret_key}"
