include:
  - u-at-proto/traefik/compose.yml
  - u-at-proto/database/compose.yml
  # - u-at-proto/observability/compose.yml
  - u-at-proto/plc/compose.yml
  - tests/compose/maildev.yml
  - tests/compose/pds.yml
  - tests/compose/ozone.yml
  - tests/compose/hepa.yml
  - u-at-proto/relay/compose.yml
  # - u-at-proto/moderation/compose.yml
  - u-at-proto/appview/compose.yml
  # - u-at-proto/feedgen/compose.yml
  # - u-at-proto/social/compose.yml
  # - u-at-proto/tests/compose.yml
