apiVersion: v1
kind: Service
metadata:
  name: pds-headless
  namespace: ${namespace}
  labels:
    app:  ${namespace}
    app.kubernetes.io/name:  ${namespace}
    app.kubernetes.io/component: server
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app:  ${namespace}
    app.kubernetes.io/name:  ${namespace}
  ports:
    - name: http
      port: 2583
      targetPort: 2583
      protocol: TCP
      appProtocol: http

# TODO: Add app.kubernetes.io/managed-by: terraform label for consistency
