apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: ${objectstore_name}
  namespace: ${namespace}
spec:
  instanceSidecarConfiguration:
    env:
      - name: AWS_DEFAULT_REGION
        value: ${s3_region}
      # Fix for XAmzContentSHA256Mismatch with S3-compatible storage (UpCloud, Ceph, etc)
      # Newer boto3 versions enforce checksums that non-AWS services don't support
      # See: https://www.beyondwatts.com/posts/debugging-barman-xamzcontentsha256mismatch-error-after-upgrading-to-postgresql175/
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
  configuration:
    destinationPath: "${destination_path}"
    endpointURL: "${endpoint_url}"
    s3Credentials:
      accessKeyId:
        name: ${secret_name}
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: ${secret_name}
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip # TODO: Benchmark compression overhead vs storage savings for your workload
      maxParallel: 4 # TODO: Tune based on network bandwidth and storage IOPS capacity
    data:
      compression: gzip
      jobs: 2 # TODO: Increase jobs for faster backups if cluster has multiple cores
    # TODO: Add encryption configuration for data at rest in S3
